### ISSUE TITLE
Unexpected behavior with `LockedAxes` and rotations after upgrading from `0.1.0` to `0.1.1`

### ISSUE THREAD

**Issue by piedoom** [Jondolf/avian#474] opened 2024-07-31 00:51 UTC
Hello! I made a post in Discord, and managed to make a pretty simple reproduction of the issue. In `0.1.0`, setting the `AngularVelocity` appears to function normally, but in `0.1.1`, it appears to "stick" due to the `LockedAxes` component, which should not be affecting the rotation.

https://github.com/piedoom/av-repro

Specifically, the situation that causes the issue must have the following:

- The entity must have a Transform with some rotation other than Y is up. In this example, Z is considered up. (I've actually only tested with Z up, but assume it can happen with other rotations?)
- There must be LockedAxes. In my case, every rotation but around the Z axis is locked.

### `0.1.0`

https://github.com/user-attachments/assets/f553ae98-23e2-46c5-b2d6-63af188c535e

### `0.1.1`

https://github.com/user-attachments/assets/546bd54d-10d9-4055-a322-72fcb828307b

Thank you and apologies if this is user error!

I noticed I could fix the behavior by specifying a regular transform for the entity, and then specifically adding a `Rotation` with `Z` as up (though this rotates the forward vector of my object downward, which is unwanted). Anyways, I'm wondering if there's perhaps a mismatch of the transform rotation and the physics rotation that is causing this

**Comment by Jondolf** [comment] 2024-08-10 17:47
Thank you for the useful reproduction! This seems to have been a regression caused by #420, as it applies the locked axes incorrectly. This should be fixed by #485.

**Closed** 2024-08-10 18:14 UTC
Labels: C-Bug, A-Dynamics
