### ISSUE TITLE
Infinite Bouncing Ball fails

### ISSUE THREAD

**Issue by Wolftousen** [Jondolf/avian#594] opened 2024-12-13 22:03 UTC
This is somewhat related to #200 , but that was specific to XPBD.

I've tried to make the same thing happen in Avian2d, but am failing to get an infinite bounce no matter what.  The balls bounce decays rather quickly.

I did try without `parallel` and without `simd` and got the same results.  I was unable to try with `f64` due to build errors that I haven't had time to look into.

It also happens in release mode and debug mode.

My `Cargo.toml`:
```toml
[package]
name = "game"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15.0", features = ["dynamic_linking"] }
leafwing-input-manager = "0.15.1"
leafwing_abilities = "0.9.0"
avian2d = { git = "https://github.com/Jondolf/avian", branch = "main", features = ["2d", "parallel", "simd"]}
bevy_prototype_lyon = "0.13.0"

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

```

My code:
```rust
use bevy::{color::palettes::css::*, prelude::*};
use bevy_prototype_lyon::prelude::*;
use avian2d::prelude::*;

fn main() {
    App::new()
        .insert_resource(ClearColor(Color::srgb(0., 0., 0.)))
        .insert_resource(Gravity(Vec2::NEG_Y * 98.1))
        .insert_resource(Time::<Fixed>::from_hz(120.0))
        .add_plugins((DefaultPlugins, ShapePlugin, PhysicsPlugins::default()))
        .add_systems(Startup, spawn)
        .run();
}

fn spawn(mut commands: Commands) {
    //camera
    commands.spawn((Camera2d, Msaa::Sample4));

    //shapes
    let circle = shapes::Circle {
        radius: 10.0,
        ..Default::default()
    };

    let rect = shapes::Rectangle {
        extents: [50.0, 5.0].into(),
        origin: RectangleOrigin::Center,
        ..Default::default()
    };

    //ball
    commands.spawn((
        Collider::circle(10.0),
        Friction::ZERO.with_combine_rule(CoefficientCombine::Min),
        Mass(1.0),
        AngularVelocity(0.0),
        LinearVelocity([0.0, 0.0].into()),
        ColliderDensity(0.0),
        AngularDamping(0.0),
        LinearDamping(0.0),
        SweptCcd::default(),
        RigidBody::Dynamic,
        Restitution::PERFECTLY_ELASTIC.with_combine_rule(CoefficientCombine::Max),
        ShapeBundle {
            path: GeometryBuilder::build_as(&circle),
            ..default()
        },
        Fill::color(GREEN),
    ));

    //start indicator
    commands.spawn((
        ShapeBundle {
            path: GeometryBuilder::build_as(&rect),
            transform: Transform::from_xyz(0.0, 15.0, 0.0),
            ..default()
        },
        Fill::color(RED),
    ));

    //floor
    commands.spawn((
        RigidBody::Static,
        Collider::rectangle(50.0, 5.0),
        ShapeBundle {
            path: GeometryBuilder::build_as(&rect),
            transform: Transform::from_xyz(0.0, -100.0, 0.0),
            ..default()
        },
        Fill::color(BLUE),
        Friction::ZERO.with_combine_rule(CoefficientCombine::Min),
        Restitution::PERFECTLY_ELASTIC.with_combine_rule(CoefficientCombine::Max),
    ));
}
```

**Comment by Wolftousen** [comment] 2024-12-14 01:51
Add some logging to the collision event and found a pretty significant deviation in the applied impulse:

Bounce | End Impulse | Difference
-- | -- | --
1 | 130.86705 |  
2 | 130.04947 | 0.81758
3 | 129.23192 | 0.81755
4 | 128.44592 | 0.786
5 | 127.59684 | 0.84908
6 | 126.81093 | 0.78591
7 | 125.96188 | 0.84905
8 | 125.16499 | 0.79689
9 | 124.326935 | 0.838055
10 | 123.51906 | 0.807875
11 | 122.691986 | 0.827074
12 | 121.88411 | 0.807876
13 | 121.05704 | 0.82707
14 | 120.28212 | 0.77492
15 | 119.42209 | 0.86003
16 | 118.64717 | 0.77492
17 | 117.78714 | 0.86003
18 | 116.97926 | 0.80788
19 | 116.15219 | 0.82707
20 | 115.3347 | 0.81749
21 | 114.51724 | 0.81746
22 | 113.71898 | 0.79826
23 | 112.88229 | 0.83669
24 | 112.106 | 0.77629
25 | 111.247345 | 0.858655
26 | 110.46007 | 0.787275
27 | 109.6124 | 0.84767
28 | 108.80315 | 0.80925
29 | 107.97745 | 0.8257
30 | 107.179184 | 0.798266
31 | 106.3425 | 0.836684
32 | 105.55522 | 0.78728
33 | 104.70755 | 0.84767
34 | 103.90791 | 0.79964
35 | 103.0726 | 0.83531
36 | 102.28395 | 0.78865
37 | 101.43765 | 0.8463

Average Deviation: 0.8174833333

This seems a bit high to just be a rounding error.

I did manage to try it with `f64`, but made no difference.   I also increased the `substeps` to 32 and that also made no difference.

**Comment by Wolftousen** [comment] 2024-12-14 03:05
After changing my restitution to `1.006249599073`, I tried a few things to see if that value would be stable:

Change | Result | Notes
--- | --- | ---
2x mass of ball | stable |
20x mass of ball | stable |
10x gravity (981) | unstable | to get stability, new value for restitution was `1.01999980917146408790443111199947`
100x gravity (9810) | unstable | to get stability, new value for restitution was `1.06249999522171290353876884260177`, but this caused the ball to go a little to high, but was stable at the new height.  An interesting observation is that if I changed it to 1.062, it became unstable and the ball started to climb in height instead of decrease, even though the restitution was lower.

**Comment by Wolftousen** [comment] 2024-12-14 03:09
It should also be noted that if gravity is left at the default of 9.81 (and you do not change the length unit) that restitution 1 is also not stable and will cause the ball to decrease in height, all be it very slowly compared to other values of gravity.

So there is some kind of direct correlation to gravity here, maybe not causation though.

**Comment by Jondolf** [comment] 2024-12-14 14:29
Hi! Could you try setting the [`SpeculativeMargin`](https://docs.rs/avian2d/0.1.2/avian2d/dynamics/ccd/struct.SpeculativeMargin.html) of the ball to zero while `SweptCcd` is enabled? I suspect that this problem is caused by speculative collision, which applies a predictive impulse to prevent tunneling, but it has the downside of absorbing some of the impact and making restitution a bit worse. With `SweptCcd`, you probably don't need speculative collision either way in this case, and it should work better with restitution.

**Comment by Wolftousen** [comment] 2024-12-14 16:32
That worked and resulted in stability.

May want to add a note to the speculative documentation about the impulse and restitution conflicts and how to counter them.

Also the docs about swept and speculative ccd make it seem like enabling swept on an entity disables speculative.  Is there a way to disable speculative other than setting the margin to zero?

**Comment by Jondolf** [comment] 2024-12-14 18:19
> May want to add a note to the speculative documentation about the impulse and restitution conflicts and how to account for them.

Yup, agreed!

> Also the docs about swept and speculative ccd make it seem like enabling swept on an entity disables speculative.

The [CCD](https://docs.rs/avian2d/0.1.2/avian2d/dynamics/ccd/index.html) docs do briefly mention: "Speculative collision is enabled by default, but swept CCD is opt-in with the `SweptCcd` component. The two approaches can also be used together." and: "Swept CCD might also not account for chain reactions properly, so if a fast-moving body bumps into another body, making it a fast-moving body that potentially bumps into even more bodies, the collisions might not propagate accurately. However, speculative contacts do detect secondary collisions quite well, so using the two together can help mitigate the issue."

Having both enabled can be valuable in some cases. Swept CCD has the problem of ["time loss"](https://docs.rs/avian2d/0.1.2/avian2d/dynamics/ccd/index.html#caveats-of-swept-ccd), and successive contacts within a single timestep may not be handled properly. Speculative collision can help with that, while still having swept CCD as a sort of safety net to fully prevent tunneling for more complicated scenarios.

> Is there a way to disable speculative other than setting the margin to zero?

Speculative collision is quite cheap, and setting the margin to zero is basically equivalent to disabling it. You can disable it globally by setting [`NarrowPhaseConfig::default_speculative_margin`](https://docs.rs/avian2d/0.1.2/avian2d/collision/narrow_phase/struct.NarrowPhaseConfig.html#structfield.default_speculative_margin) to zero.

**Comment by Jondolf** [comment] 2024-12-20 20:47
Added some brief documentation on how speculative collision can affect restitution in #598. Closing this issue now since it seems to be resolved.

**Closed by Jondolf** 2024-12-20 20:47 UTC
Labels: C-Bug, A-Dynamics
